### ISSUE TITLE
Issue with adding a second or third cluster

### ISSUE THREAD

**Issue by cbluth** [grafana/kubernetes-app#48]
Hello, I seemingly have added my first k8s cluster without issue, I have explained the process I used to add the first cluster here: https://github.com/grafana/kubernetes-app/issues/46#issuecomment-435806954

My issue is that when I want to add another cluster, my dashboards end up looking like this:
>
![image](https://user-images.githubusercontent.com/6709636/47989581-ac70b400-e0e5-11e8-84d2-31eaf45e2bac.png)

>
>
![image](https://user-images.githubusercontent.com/6709636/47989689-ee99f580-e0e5-11e8-862e-f57457c73efe.png)

**Comment by cbluth** [comment]
I see this: https://github.com/grafana/kubernetes-app/blob/ddf616e74c2146e72529316f4fb0348b787e38f4/dist/components/clusters/clusterConfig.ts#L481

Does this mean that the dashboard can only connect to the cluster that it is running in? or can it still connect to clusters outside the current cluster?

**Comment by cbluth** [comment]
I think I found the solution to my issue:

1) make sure prometheus-server is installed on each cluster.
2) add config for prometheus federation, see here: https://prometheus.io/docs/prometheus/latest/federation/
my config looks like this:
```
    - job_name: federate
      scrape_interval: 15s
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]':
          - '{job="prometheus"}'
          - '{job=~"^kubernetes.+"}'
          - '{__name__=~"job:.*"}'
      static_configs:
        - targets:
          - 'ip-of-other-prometheus-server:9090'
```
