### ISSUE TITLE
Add info that kubernetes legacy authorization is a requirement to run the plugin

### ISSUE THREAD

**Issue by JCMais** [grafana/kubernetes-app#52]
After some debugging on why the plugin was working on our dev cluster but was not working for our staging one, I've found that it requires legacy authorization to be enabled on the cluster.

See https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control for more details on the legacy authorization model.

On GKE this can be changed here:
![image](https://user-images.githubusercontent.com/1041647/48875778-29887280-ede2-11e8-8bdf-96186b81e6bd.png)

It would be much better if the plugin could support token authentication (like mentioned in one of the issues below), or allow to use service account directly (in case it was deployed to the same cluster it's going to connect).

Currently I've just removed everything related to the Kubernetes Datasource provided by this plugin and changed the dashboards according, so basically the plugin is not used anymore.

Most of the variables can be replaced to use some prometheus metric:

`$node` can be `label_values(kube_node_info, node)`
`$namespace` can be `label_values(kube_namespace_created, namespace)`

Both metrics are from [`kube-state-metrics`](https://github.com/kubernetes/kube-state-metrics).

There are other issues that are probably related to this one:
https://github.com/grafana/kubernetes-app/issues/12
https://github.com/grafana/kubernetes-app/issues/22
https://github.com/grafana/kubernetes-app/issues/34
https://github.com/grafana/kubernetes-app/issues/41
https://github.com/grafana/kubernetes-app/issues/47

**Comment by azelezni** [comment]
could you share the modified dashboards?

**Comment by JCMais** [comment]
@azelezni yes, here they are https://gist.github.com/JCMais/a0750ee1cc4186909d3caddcf5e08d30

You probably will need to change the datasources to point to the correct prometheus one.

**Comment by afking** [comment]
Solved the issue by running kubectl as a sidecar to grafana. Would be nice to use without kubectl api access though.

```yaml
        - name: kubectl
          image: gcr.io/cloud-builders/kubectl@sha256:1239b60476a8dd727bde2d555c1b6efef420636991f9d4d376783645100dec30
          imagePullPolicy: IfNotPresent
          command:
            - kubectl
            - proxy
```
